### ISSUE TITLE
Interest in new maintainer + implementation parity w/ eslint-plugin-jest

### ISSUE THREAD

**Issue by G-Rath** [mattphillips/eslint-plugin-jest-extended#1]
Hi! I'm one of the core maintainers for `eslint-plugin-jest`, and I was wondering if you'd be interested in having me as a maintainer, and ideally implementing a similar TypeScript setup as we've got for `eslint-plugin-jest`, as the core of `eslint-plugin-jest` can be identical to `eslint-plugin-jest-extended`, just with different rules.

The majority of rules I have in mind for now are "prefer-x" ones, and then going from there.

Alternatively, I'm happy to take ownership of the repo :)

Cheers!

**Comment by chrishiste** [comment]
Hello @mattphillips the npm package is 404'ing for me today. 

If you don't have time to maintain the project it would be awesome if you could give ownership of the repo to @G-Rath.

In any case thanks for your work on this 😃

**Comment by chrishiste** [comment]
@G-Rath just saw the last commit is 2 years old and you're question is couple months old, might be time for a fork. What do you think?

**Comment by G-Rath** [comment]
@chrishiste possibly - I'm planning to look into jest-extended in a few months when I've finished the first stage of my current big project, and so will have a bunch of tests to look into.

There were talks on `eslint-plugin-jest` about including `jest-extended` rules in there, which I have no problem against, but it was before my time and is just sort of sitting there, so that was the first thing I was going to look into.

@SimenB thoughts?

------

Here's the issue I was thinking of: https://github.com/jest-community/eslint-plugin-jest/issues/19

It was looking like we'd move to a mono-repo at some point, which would include a plugin for this.

I think for now, I'll add this on my radar to action sometime next month - effectively I'll clone `eslint-plugin-jest` without the rules since I think it makes sense to just reuse it's structure and pipeline to reduce overhead, and contact npm about taking over the package.

**Comment by G-Rath** [comment]
> Hello @mattphillips the npm package is 404'ing for me today.

Oh, it seems like the package might have actually been deleted - so guess I've got my weekend planned for me :joy:

**Comment by SimenB** [comment]
I have no issues moving to a monorepo and having this in the "normal" repo. Not sure how well lerna/yarn workspace works with semantic release, tho

**Comment by G-Rath** [comment]
Awesome!

> I have no issues moving to a monorepo

What's the best way to kick off such a move?

**Comment by mattphillips** [comment]
Hey guys 👋 

I completely forgot that I even started this repo - been a while! 

I'd be happy for any help @G-Rath 😄 

I don't think I actually published this back in the day - I've just published an empty package so no one sits on it! Happy to grant the relevant people publish access and transfer the repo over to `jest-community` or to a monorepo.

**Comment by G-Rath** [comment]
> I've just published an empty package so no one sits on it!

That's possibly why it was deleted; npm is now allowing deleting packages that have next-to-no downloads a week, and only one contributor 🤔

> Happy to grant the relevant people publish access and transfer the repo over to jest-community or to a monorepo.

That'd be awesome! I'm not a member of the `jest-community` team on github, so that'd probably be better handled by someone who is (like @SimenB), but if you give me access to this repo I can look to pull across some of the things we've got in `eslint-plugin-jest` and get a version published over the few days.

**Comment by mattphillips** [comment]
> That's possibly why it was deleted; npm is now allowing deleting packages that have next-to-no downloads a week, and only one contributor 🤔

I don't think it was deleted, I just never published it 🤣 there is something there now though (I published it as of 15 minutes ago).

---

I can sort all of the `jest-community` stuff out, I think the only decision is around monorepo in`eslint-jest` vs seperate repo inside of the org. I've not got too much of a preference (although it would be great to re-use the sharable bits of the rules). @SimenB any preference?

**Comment by SimenB** [comment]
I've been subscribed to https://github.com/semantic-release/semantic-release/issues/193 for years at this point, so might be easier to just have separate packages and copy any utils over 👍

**Comment by mattphillips** [comment]
@G-Rath I've created the repo in the community org [here](https://github.com/jest-community/eslint-plugin-jest-extended) and added you as a collaborator. When we are ready to push something out I'll sort out the semantic release rights to the package 😄

**Comment by SimenB** [comment]
Probably the kick in the behind I need to create a jest community npm bot we can use rather than personal accounts

**Comment by chrishiste** [comment]
@G-Rath @SimenB @mattphillips thanks you guys are legends 😃

**Comment by G-Rath** [comment]
I'm going to close this since we've [moved it](https://github.com/jest-community/eslint-plugin-jest-extended) (tho it does still need to be setup to publish to npm 😉)

@mattphillips I'd say you can archive this repo now?
